'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useMemo } from 'react';
import { BoundaryMap } from '@/components/boundary-map';
import { CaseGrid } from '@/components/case-grid';
import { Badge, Callout, EmptyState, Kpi, Panel } from '@/components/ui';
import { deriveBoundary, deriveCases, isMinimizedReplay } from '@/lib/derive';
import { ms } from '@/lib/format';
import { useRunStream } from '@/lib/run-stream';

export default function ExplorationPage() {
  const { runId } = useParams<{ runId: string }>();
  const stream = useRunStream();

  // Replays of the minimized scenario run against both targets, so they are shown in the
  // verification act rather than plotted here where they would misread as boundary data.
  const cases = useMemo(
    () => deriveCases(stream.results.filter((result) => !isMinimizedReplay(result))),
    [stream.results],
  );
  const exploredCases = useMemo(() => cases.filter((item) => item.explored), [cases]);
  const boundary = useMemo(() => deriveBoundary(stream.results), [stream.results]);

  if (exploredCases.length === 0) {
    return (
      <EmptyState title="No adaptive cases yet">
        Exploration starts automatically once a failure is discovered.
      </EmptyState>
    );
  }

  const bracketKnown =
    boundary.lastPassingPauseMs !== undefined && boundary.firstFailingPauseMs !== undefined;

  return (
    <>
      <header className="vf-col" style={{ gap: 8 }}>
        <p className="vf-eyebrow">Adaptive exploration</p>
        <h1 className="vf-h2">
          VoiceFuzz found one failure, so it generated nearby tests to locate the exact boundary.
        </h1>
        <p className="vf-lede">
          Each new case varies the pause around the failing point. The dashed line is the lowest
          pause value observed to fail — everything to its left still passed.
        </p>
      </header>

      <div className="vf-split vf-split--3">
        <Kpi
          label="Adaptive cases"
          value={exploredCases.length}
          note="Generated around the failure"
        />
        <Kpi
          label="Last passing pause"
          value={ms(boundary.lastPassingPauseMs)}
          tone={boundary.lastPassingPauseMs !== undefined ? 'pass' : undefined}
          note="Highest pause that still behaved"
        />
        <Kpi
          label="First failing pause"
          value={ms(boundary.firstFailingPauseMs)}
          tone={boundary.firstFailingPauseMs !== undefined ? 'fail' : undefined}
          note="Lowest pause that broke the invariant"
        />
      </div>

      <Panel
        title="Pause × interruption map"
        caption="Every dot is a real evaluated case"
        actions={
          bracketKnown ? (
            <Badge tone="warn">
              Boundary between {boundary.lastPassingPauseMs} and {boundary.firstFailingPauseMs} ms
            </Badge>
          ) : null
        }
      >
        <div className="vf-scroll-x">
          <BoundaryMap cases={cases} boundary={boundary} />
        </div>
        {bracketKnown ? (
          <Callout variant="info">
            Behaviour flips between <strong>{boundary.lastPassingPauseMs} ms</strong> and{' '}
            <strong>{boundary.firstFailingPauseMs} ms</strong> of silence. That bracket is as tight
            as the grid this run executed — it is the observed boundary, not an interpolated
            estimate.
          </Callout>
        ) : (
          <Callout>
            The run has not yet produced both a passing and a failing pause value, so no boundary
            can be claimed.
          </Callout>
        )}
      </Panel>

      <Panel title="Adaptive cases" caption="Dashed border = generated by exploration">
        <CaseGrid cases={exploredCases} />
      </Panel>

      <div className="vf-row">
        <Link className="vf-btn vf-btn--primary" href={`/run/${runId}/minimize`}>
          Minimize to a counterexample
        </Link>
        <Link className="vf-btn vf-btn--secondary" href={`/run/${runId}/failure`}>
          Back to failure
        </Link>
      </div>
    </>
  );
}
